name: Create Release
on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: Create a draft release
        required: true
        type: boolean
        default: true
  push:
    branches:
      - main
concurrency:
  group: release
  cancel-in-progress: false
run-name: Release ${{ github.sha }} by @${{ github.actor }}
permissions:
  contents: write
  id-token: write
  pull-requests: read
jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Get Release Version
        id: get-version
        uses: nullify-platform/github-actions/actions/release-version@main
      - run: |
          echo "config-file-parser @ ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "VERSION:   ${{ steps.get-version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "SHORT_SHA: $(git rev-parse --short HEAD)" >> $GITHUB_STEP_SUMMARY
  release:
    if: ${{ needs.get-version.outputs.version != 'undefined' || (github.event_name == 'workflow_dispatch' && needs.get-version.outputs.version != 'undefined') }}
    runs-on: ubuntu-latest
    needs: [ get-version ]
    steps:
      - uses: actions/checkout@v3
      - name: Generate Release Tag
        run: echo "RELEASE_TAG=v${{ needs.get-version.outputs.version }}" >> $GITHUB_ENV
      - name: Generate Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          generate_release_notes: true
          append_body: true
          tag_name: ${{ env.RELEASE_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}